// This is a TEMPLATE — generated by WebForge for each business
// Claude Fable 5 style: editorial, calm, paper texture

export default function TemplateSite() {
  return (
    <main className="min-h-screen bg-[#FFFCF5] text-[#141413]">
      <section className="mx-auto max-w-[1280px] px-8 py-24">
        <p className="font-mono text-[11px] tracking-widest text-[#A8A6A0]">ATELIER NO. 5 • KYOTO</p>
        <h1 className="mt-6 font-serif text-[64px] leading-[0.9] tracking-[-0.03em]">
          Objects made to be <span className="italic font-light">lived with.</span>
        </h1>
        <p className="mt-6 max-w-[480px] text-[17px] leading-[1.6] text-[#575551]">
          A quiet ceramic studio in Kyoto, making wabi-sabi tableware for slow mornings.
        </p>
      </section>
    </main>
  )
}
